ssh-config: ENC[AES256_GCM,data:E7uTSVwWtIuKTEkcQHBYHORE5kkQoO7D/r9Yxz80xifvOwsTF79mr4orwO0jGFqwDTAoUeI/2WFQjhbbuyLdqY2AZeMSWgam2mVo1Zwtfk7sGiYRTzYGXk0nW+bp8gLPRTYA7tvqSKl0hA96T/HHjrL6G0mFGa89kP1ZbQilJJXPKNzZMfHoiT3GlzX3d47gxCK2J/L+DQqwRwNTATxQf6wPToR/pM6pITyhIg==,iv:KEH4R5bHFeB67aVvFM0hXYO2lBlYWwAKMMDSRRhFqDY=,tag:j6vJE1xc9t1G7lerK3aA8Q==,type:str]
sops:
    age:
        - recipient: age1p82q5dgmtgr6t62vha80l4ul5kj5ypfgkal023vnvqwrlyeau9rsech6pj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVDhwNzhIZTBjaEtRRXM0
            OGp6NWl0Wm9ZZjVhZFFyNXhXcjFIZGdISVJVCkZwUHZvbWIrdG1JNk1ubXJVNHVB
            ZHVqaG9KVXE2K2J1ZlpSUS80S0VwNFkKLS0tIDVDK1M5cGQrbC9EUCt0eFgveFNP
            YmNFNGYvRW1PYVZDbjRuYXVyM2VrVVkKd8Am7EbCghAyKKuz9U3o4PAxKgKPYyS9
            DY2ycS6q4r3hk1HgeN16HB6IorE0xiGVpi/L8DTlBa9NGQXf//KkIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T16:31:23Z"
    mac: ENC[AES256_GCM,data:Y6/nq1luxhs2LX2qxYWLYbADrIw0HtVJaLocmH0qf86VJJ4umW8huwrZ9n5dbRjaCbxJEfoFzNw+AKnkd8QwUYgIdVmTZxIp01P1VlEMn+aTz44fbM/CT9U0d62em+ZxcT+uOoJK7ljHaiDkqMMkYsj16SJx3nTptnSjSqPc6o8=,iv:15IcbXj81q780F4cq4CLzTViYZWLt0SpqGhmJxwcCrQ=,tag:jVVV5tDmNGRcwz9IldWZ1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
